name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Create ZIP
        run: |
          cd custom_components
          zip -r ../ultra_jack.zip ultra_jack/
          cd ..

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ultra_jack.zip